spring.data.mongodb.uri=mongodb://hkouki:password@localhost:27017/lets_play_db?authSource=admin
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=letsplay123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=letsplay

# JWT Configuration
app.jwt.secret=rKY5Bk8zY7ANLejsGVVwCc5IrAj000N2iKMRn7uUES0=
app.jwt.expiration=86400000